name: projectTeamO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: gcc code.c -o code -std=c99; ./code
    - name: make
      run: gcc code.c -o code -std=c99; ./code
